name: segmentation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - plotly
  - matplotlib
  - nbformat
  - ipykernel
#conda env create -f conda_env.yaml